spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/class_management?useSSL=true&Unicode=true&characterEncoding=UTF-8
    username: issunjh
    password: 123456

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.issunjh.ClassManagement.bean

server:
  port: 8081
